USE biblioteca_marco_migracao;

INSERT INTO autor (nome, nacionalidade) VALUES
('Machado de Assis', 'Brasil'),
('José Saramago', 'Portugal'),
('George Orwell', 'Reino Unido'),
('Jane Austen', 'Reino Unido'),
('Jorge Luis Borges', 'Argentina'),
('Gabriel García Márquez', 'Colômbia'),
('Franz Kafka', 'Alemanha'),
('J.K. Rowling', 'Reino Unido'),
('Haruki Murakami', 'Japão'),
('Ernest Hemingway', 'EUA'),
('Clarice Lispector', 'Brasil'),
('Eça de Queiroz', 'Portugal'),
('William Shakespeare', 'Reino Unido'),
('Virginia Woolf', 'Reino Unido'),
('Albert Camus', 'França'),
('Italo Calvino', 'Itália'),
('Stephen King', 'EUA'),
('Carlos Drummond de Andrade', 'Brasil'),
('Margaret Atwood', 'Canadá'),
('Mia Couto', 'Moçambique'),
('Paulo Coelho', 'Brasil'),
('Oscar Wilde', 'Irlanda'),
('Fiódor Dostoiévski', 'Rússia'),
('Lev Tolstói', 'Rússia'),
('Graciliano Ramos', 'Brasil'),
('José de Alencar', 'Brasil'),
('Fernando Pessoa', 'Portugal'),
('Agatha Christie', 'Reino Unido'),
('Julio Cortázar', 'Argentina'),
('Mario Vargas Llosa', 'Peru'),
('H.P. Lovecraft', 'EUA'),
('Cecília Meireles', 'Brasil'),
('Rubem Braga', 'Brasil'),
('Albert Einstein', 'Alemanha'),
('Sun Tzu', 'China'),
('Homer', 'Grécia'),
('Platão', 'Grécia'),
('Aristóteles', 'Grécia'),
('Sigmund Freud', 'Áustria'),
('Jean-Paul Sartre', 'França'),
('Simone de Beauvoir', 'França'),
('Umberto Eco', 'Itália'),
('João Cabral de Melo Neto', 'Brasil'),
('Carlos Fuentes', 'México'),
('José Martí', 'Cuba'),
('Chimamanda Ngozi Adichie', 'Nigéria'),
('José Hernández', 'Argentina'),
('Rubem Fonseca', 'Brasil'),
('Monteiro Lobato', 'Brasil'),
('Lima Barreto', 'Brasil'),
('Mo Yan', 'China'),
('André Gide', 'França'),
('Thomas Mann', 'Alemanha'),
('Hermann Hesse', 'Alemanha'),
('Khaled Hosseini', 'Afeganistão'),
('Kazuo Ishiguro', 'Reino Unido'),
('Toni Morrison', 'EUA'),
('Mário Quintana', 'Brasil'),
('Rupi Kaur', 'Canadá'),
('Lygia Fagundes Telles', 'Brasil'),
('José Lins do Rego', 'Brasil'),
('Emily Brontë', 'Reino Unido'),
('Charlotte Brontë', 'Reino Unido'),
('Mary Shelley', 'Reino Unido'),
('Bram Stoker', 'Irlanda'),
('James Joyce', 'Irlanda'),
('Dante Alighieri', 'Itália'),
('Giovanni Boccaccio', 'Itália'),
('Nicolau Maquiavel', 'Itália'),
('Voltaire', 'França'),
('Victor Hugo', 'França'),
('Alexandre Dumas', 'França'),
('Honoré de Balzac', 'França'),
('Jules Verne', 'França'),
('Edgar Allan Poe', 'EUA'),
('Mark Twain', 'EUA'),
('Jack London', 'EUA'),
('Herman Melville', 'EUA'),
('John Steinbeck', 'EUA'),
('Erico Verissimo', 'Brasil'),
('Jorge Amado', 'Brasil'),
('Nelson Rodrigues', 'Brasil'),
('Rachel de Queiroz', 'Brasil'),
('Cyro dos Anjos', 'Brasil'),
('Fernando Sabino', 'Brasil'),
('Murilo Rubião', 'Brasil'),
('Moacyr Scliar', 'Brasil'),
('Orhan Pamuk', 'Turquia'),
('José Donoso', 'Chile'),
('Isabel Allende', 'Chile'),
('Pablo Neruda', 'Chile'),
('Mario Benedetti', 'Uruguai'),
('Juan Rulfo', 'México'),
('Octavio Paz', 'México'),
('J. R. R. Tolkien', 'Reino Unido'),
('C.S. Lewis', 'Reino Unido'),
('Neil Gaiman', 'Reino Unido'),
('Douglas Adams', 'Reino Unido');




INSERT INTO livro (titulo, ano_publicacao, id_autor_fk) VALUES
('Dom Casmurro', 1899, 1),
('Memorial do Convento', 1982, 2),
('1984', 1949, 3),
('Orgulho e Preconceito', 1813, 4),
('Ficções', 1944, 5),
('Cem Anos de Solidão', 1967, 6),
('A Metamorfose', 1915, 7),
('Harry Potter e a Pedra Filosofal', 1997, 8),
('Kafka à Beira-Mar', 2002, 9),
('O Velho e o Mar', 1952, 10),
('A Hora da Estrela', 1977, 11),
('Os Maias', 1888, 12),
('Hamlet', 1603, 13),
('Mrs. Dalloway', 1925, 14),
('O Estrangeiro', 1942, 15),
('Se um Viajante numa Noite de Inverno', 1979, 16),
('O Iluminado', 1977, 17),
('Alguma Poesia', 1930, 18),
('O Conto da Aia', 1985, 19),
('Terra Sonâmbula', 1992, 20),
('O Alquimista', 1988, 21),
('O Retrato de Dorian Gray', 1890, 22),
('Crime e Castigo', 1866, 23),
('Guerra e Paz', 1869, 24),
('Vidas Secas', 1938, 25),
('Iracema', 1865, 26),
('Mensagem', 1934, 27),
('Assassinato no Expresso do Oriente', 1934, 28),
('Rayuela', 1963, 29),
('Conversa na Catedral', 1969, 30),
('O Chamado de Cthulhu', 1928, 31),
('Romanceiro da Inconfidência', 1953, 32),
('A Cidade e as Serras', 1901, 12),
('O Mundo Como Eu Vejo', 1934, 34),
('A Arte da Guerra', -500, 35),
('Ilíada', -750, 36),
('A República', -380, 37),
('Ética a Nicômaco', -340, 38),
('A Interpretação dos Sonhos', 1899, 39),
('A Náusea', 1938, 40),
('O Segundo Sexo', 1949, 41),
('O Nome da Rosa', 1980, 42),
('Morte e Vida Severina', 1955, 43),
('Aura', 1962, 44),
('Versos Sencillos', 1891, 45),
('Americanah', 2013, 46),
('Martín Fierro', 1872, 47),
('Agosto', 1990, 48),
('Sítio do Picapau Amarelo', 1920, 49),
('Triste Fim de Policarpo Quaresma', 1911, 50),
('Mudança', 1987, 51),
('Os Moedeiros Falsos', 1925, 52),
('A Montanha Mágica', 1924, 53),
('Sidarta', 1922, 54),
('O Caçador de Pipas', 2003, 55),
('Os Despojos do Dia', 1989, 56),
('Amada', 1987, 57),
('Caderno H', 1973, 58),
('Outros Jeitos de Usar a Boca', 2014, 59),
('As Meninas', 1973, 60),
('Menino de Engenho', 1932, 61),
('Morro dos Ventos Uivantes', 1847, 62),
('Jane Eyre', 1847, 63),
('Frankenstein', 1818, 64),
('Drácula', 1897, 65),
('Ulisses', 1922, 66),
('A Divina Comédia', 1320, 67),
('Decamerão', 1353, 68),
('O Príncipe', 1532, 69),
('Cândido', 1759, 70),
('Os Miseráveis', 1862, 71),
('O Conde de Monte Cristo', 1844, 72),
('A Comédia Humana', 1848, 73),
('Vinte Mil Léguas Submarinas', 1870, 74),
('O Corvo', 1845, 75),
('As Aventuras de Tom Sawyer', 1876, 76),
('Caninos Brancos', 1906, 77),
('Moby Dick', 1851, 78),
('As Vinhas da Ira', 1939, 79),
('O Tempo e o Vento', 1949, 80),
('Capitães da Areia', 1937, 81),
('Vestido de Noiva', 1943, 82),
('O Quinze', 1930, 83),
('O Amanuense Belmiro', 1937, 84),
('O Encontro Marcado', 1956, 85),
('O Ex-Mágico da Taberna Minhota', 1947, 86),
('O Centauro no Jardim', 1980, 87),
('Neve', 2002, 88),
('O Obsceno Pássaro da Noite', 1970, 89),
('A Casa dos Espíritos', 1982, 90),
('Vinte Poemas de Amor e uma Canção Desesperada', 1924, 91),
('A Trégua', 1960, 92),
('Pedro Páramo', 1955, 93),
('O Labirinto da Solidão', 1950, 94),
('O Senhor dos Anéis', 1954, 95),
('As Crônicas de Nárnia', 1950, 96),
('Deuses Americanos', 2001, 97),
('O Guia do Mochileiro das Galáxias', 1979, 98),
('Beloved', 1987, 57),
('O Livro do Desassossego', 1982, 27);